# Generated by Django 3.0.4 on 2020-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200310_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('stock_at', models.DateField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('remain_stat', models.CharField(max_length=10)),
                ('place_type', models.CharField(max_length=10)),
            ],
        ),
    ]
