# Generated by Django 3.0.4 on 2020-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mask',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mask',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='place_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='remain_stat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='stock_at',
            field=models.DateField(null=True),
        ),
    ]
