# Generated by Django 3.0.4 on 2020-03-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_checked',
        ),
    ]
