# Generated by Django 3.0.4 on 2020-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200313_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='patient',
            field=models.CharField(max_length=255),
        ),
    ]
