# Generated by Django 3.0.4 on 2020-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200313_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='patient',
            field=models.CharField(max_length=20),
        ),
    ]
