# Generated by Django 3.0.4 on 2020-03-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200313_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='number',
            new_name='code',
        ),
    ]
