# Generated by Django 3.0.4 on 2020-03-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
    ]
