# Generated by Django 3.0.4 on 2020-03-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.IntegerField(),
        ),
    ]
