# Generated by Django 3.0.4 on 2020-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200313_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
