# Generated by Django 3.0.4 on 2020-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200313_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='confirmed_date',
            field=models.DateField(null=True),
        ),
    ]
