# Generated by Django 3.0.4 on 2020-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200313_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
