# Generated by Django 3.0.4 on 2020-03-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200313_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='PatientPath',
        ),
    ]
