# Generated by Django 3.0.4 on 2020-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200314_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpath',
            name='place_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
