# Generated by Django 3.0.4 on 2020-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200314_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpath',
            name='paths',
            field=models.TextField(null=True),
        ),
    ]
